"""Serial acquisition and snapshot handoff for the Instrument firmware."""

'''
only for reference to be integrated into the main data source module, not meant to be run standalone.
'''

import serial
import time

# --- CONFIGURATION ---
# Change this to match your Arduino's port (e.g., 'COM3' for Windows, '/dev/ttyUSB0' for Linux/Mac)
SERIAL_PORT = 'COM12'
BAUD_RATE = 115200

SNAPSHOT_STD_THRESHOLD_V = 0.001 # Voltage stability threshold for sending snapshot (in volts)
SNAPSHOT_WINDOW = 20
MIN_SNAPSHOT_SEND_INTERVAL_S = 0.0

from ..utils.math import mean_std
from ..utils.math import compute_resistance_ohm


def main():
    print(f"Connecting to {SERIAL_PORT} at {BAUD_RATE} baud...")
    
    try:
        # Open serial connection
        ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=1)
        time.sleep(2)  # Give Arduino time to reset after opening connection
        
        # Clear any startup messages generated by initialize_ADS1256()
        ser.reset_input_buffer() 
        
        ser.write(b'R')
        print("Sending 'C' command to start continuous stream...")
        ser.write(b'C')

        # IF AIN0 AND AIN1 ENABLE THIS TO CHANGE OR LET USER CONFIGURE WHICH PIN TO READ
        '''
        # Ask the user for input, or press Enter for default
        cmd_input = input("Enter channel command (e.g., 'C2 4') or press Enter for default 'C': ").strip()
        
        if cmd_input == "":
            cmd_input = "C"
            
        # Add a newline \n so Arduino's parseInt() processes it instantly
        command_to_send = f"{cmd_input}\n".encode('utf-8')
        
        print(f"Sending command: '{cmd_input}' ...")
        ser.write(command_to_send)
        '''
        
        # Wait for the stream to start
        while True:
            line = ser.readline().decode('utf-8').strip()
            if line == "*STREAM_START":
                print("Stream started successfully! Press Ctrl+C to stop.\n")
                break
                
        # --- CONTINUOUS READING LOOP ---
        window = []
        last_snapshot_send = 0.0

        while True:
            line = ser.readline().decode('utf-8').strip()
            if not line:
                continue

            if line.startswith('*'):
                if line == "*FINAL":
                    final_line = ser.readline().decode('utf-8').strip()
                    print(f"FINAL: {final_line}")
                    break
                continue

            try:
                # Parse the CSV data: "Voltage,Current_mA"
                data = line.split(',')
                if len(data) != 2:
                    continue

                voltage = float(data[0])
                current_mA = float(data[1])
                print(f"Voltage: {voltage: 10.8f} V  |  Current: {current_mA:6.3f} mA")

                window.append(voltage)
                if len(window) > SNAPSHOT_WINDOW:
                    window.pop(0)

                mean, std = mean_std(window)
                now = time.time()
                if mean is None or std is None:
                    continue

                if std <= SNAPSHOT_STD_THRESHOLD_V and (now - last_snapshot_send) >= MIN_SNAPSHOT_SEND_INTERVAL_S:
                    resistance = compute_resistance_ohm(mean, current_mA)
                    if resistance is not None:
                        ser.write(f"{resistance:.5f}\n".encode('utf-8'))
                        # Debug Resistance
                        print(f"Sending R={resistance:.5f} (std={std:.6f})")
                        last_snapshot_send = now
            except ValueError:
                print(f"Failed to parse data: {line}")
                        
    except KeyboardInterrupt:
        print("\nCtrl+C detected. Stopping the stream...")
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        # Ensure we always stop the Arduino and close the port cleanly
        if 'ser' in locals() and ser.is_open:
            ser.write(b's')      # Send stop command
            time.sleep(0.5)      # Wait a moment for Arduino to process it
            ser.reset_input_buffer()
            ser.close()
            print("Serial port closed.")

if __name__ == '__main__':
    main()